# Generated by Django 5.1.5 on 2025-02-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profileskills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileSkills',
            new_name='ProfileSkill',
        ),
        migrations.AlterUniqueTogether(
            name='profileskill',
            unique_together={('profile', 'skill')},
        ),
    ]
