# Generated by Django 5.1.5 on 2025-02-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_profileskills_profileskill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileSkill',
        ),
    ]
