# Generated by Django 5.1.5 on 2025-02-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_skills_profileskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profileskill',
            unique_together={('profile', 'skill')},
        ),
    ]
