# Generated by Django 5.1.5 on 2025-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_social_profilesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesocial',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
