# Generated by Django 5.1.5 on 2025-02-11 19:56

import django.core.validators
import users.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profilesocial_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/default_pfp.png', upload_to=users.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webm', 'gif']), utils.validators.size_validator]),
        ),
    ]
