services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=devhub_db
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/pg_data